version: "3.9"

volumes:
  pgData:
  pgadminData:

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "gs_keycloak"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8080:8080"
    command:
      - start-dev
    depends_on:
      - postgres
    environment:
      - DB_VENDOR=POSTGRES
      - DB_ADDR=postgres
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PROXY_ADDRESS_FORWARDING=true
      - VIRTUAL_HOST=localhost
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=localhost

  postgres:
    container_name: gs_postgres
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_MULTIPLE_DATABASES=keycloak
      - POSTGRES_HOST_AUTH_METHOD=trust

    restart: always
    volumes:
      - ./docker_data/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgData:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: gs_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadminData:/var/lib/pgadmin
      - ./docker_data/pgadmin/servers.json:/pgadmin4/servers.json
